export const WORKFLOW_EVENT_TYPES = [
  "MESSAGE_RECEIVED",
  "DETERMINISTIC_ROUTE_MATCHED",
  "DETERMINISTIC_ROUTE_NOT_FOUND",
  "STATIC_RESPONSE_SENT",
  "AI_ANALYSIS_REQUIRED",
  "AI_ANALYSIS_STARTED",
  "AI_ANALYSIS_COMPLETED",
  "AI_ANALYSIS_FAILED",
  "AI_RESPONSE_GENERATED",
  "HUMAN_REVIEW_REQUIRED",
  "HUMAN_APPROVED",
  "HUMAN_REJECTED",
  "WORKFLOW_COMPLETED",
] as const;

export type WorkflowEventType = (typeof WORKFLOW_EVENT_TYPES)[number];
