export const WORKFLOW_EVENT_TYPES = [
  "MESSAGE_RECEIVED",
  "DETERMINISTIC_ROUTE_MATCHED",
  "DETERMINISTIC_ROUTE_NOT_FOUND",
  "STATIC_RESPONSE_SENT",
  "AI_ANALYSIS_REQUIRED",
  "AI_ANALYSIS_STARTED",
  "AI_RESPONSE_GENERATED",
] as const;

export type WorkflowEventType = (typeof WORKFLOW_EVENT_TYPES)[number];
